package elfa;

import org.w3c.dom.ls.LSOutput;

import java.io.File;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Scanner;
import java.util.Set;

public class Main {
    public static void main(String[] args) {
        Product shoe = new Product(Utility.createUUID(), "Shoe", new BigDecimal("49.99"));
        Product jacket = new Product(Utility.createUUID(), "Jacket", new BigDecimal("79.99"));
        Product jeans = new Product(Utility.createUUID(), "Jeans", new BigDecimal("34.99"));

        // In the main method, create either the OrderMapRepo or the OrderListRepo
        // and pass it to the constructor of ShopService (as a constructor parameter that uses the interface).
        OrderListRepo orderList = new OrderListRepo();

        Order shoeOrder = new Order(Utility.createUUID(), shoe, 2, LocalDateTime.now());
        Order jacketOrder = new Order(Utility.createUUID(), jacket, 1, LocalDateTime.now());
        Order jeansOrder = new Order(Utility.createUUID(), jeans, 4, LocalDateTime.now());

        orderList.add(shoeOrder);
        orderList.add(jacketOrder);
        orderList.add(jeansOrder);

        Scanner scanner = new Scanner(System.in);
        Utility.printCmdLineColor("red", "Enter product name");
        String productName = scanner.nextLine();
        Utility.printCmdLineColor("blue", "Enter product price");
        String productPrice = scanner.nextLine();

        Product customProduct = new Product(Utility.createUUID(), productName, new BigDecimal(productPrice));
        System.out.println(customProduct);

        // Search the internet for an EAN database in CSV format (or have one generated by ChatGPT). Use this CSV file as input.
        CSVReader csvReader = new CSVReader(new File("data.csv"));
        Set<Product> products = csvReader.readFile();
        products.forEach(System.out::println);

    }
}